# yaml-language-server: $schema=../../router-config.schema.json
supergraph:
  source: file
  path: ../supergraph.graphql
introspection:
  expression: env("DISABLE_INTROSPECTION", string!("false")) != "true"