# yaml-language-server: $schema=../../router-config.schema.json
supergraph:
  source: file
  path: ../supergraph.graphql
introspection:
  expression: .request.headers."x-enable-introspection" == "true"