# yaml-language-server: $schema=../../router-config.schema.json
supergraph:
  source: file
  path: ../supergraph.graphql
disable_introspection:
  expression: .request.headers."x-disable-introspection" == "true"