# yaml-language-server: $schema=../../router-config.schema.json
supergraph:
  source: file
  path: ../supergraph.graphql
disable_introspection:
  expression: env("DISABLE_INTROSPECTION", string!("false")) == "true"