# yaml-language-server: $schema=../../router-config.schema.json
supergraph:
  source: file
  path: ../supergraph.graphql
override_subgraph_urls:
  accounts:
    url:
      expression: env("ACCOUNTS_URL_OVERRIDE", string!(.default))
headers:
  all:
    response:
      - insert:
          name: "x-router-env"
          expression: env("ROUTER_ENV_HEADER", "default")
