# yaml-language-server: $schema=../../router-config.schema.json
supergraph:
  source: file
  path: ../supergraph.graphql
jwt:
  enabled: true
  require_authentication: true
  allowed_algorithms:
    - RS512
  jwks_providers:
    - source: file
      path: ../jwks.rsa512.alg.json
