# yaml-language-server: $schema=../../router-config.schema.json
supergraph:
  source: file
  path: ./bench/supergraph.graphql
log:
  level: info
telemetry:
  tracing:
    exporters:
      - kind: otlp
        protocol: http
        endpoint: http://localhost:404
