[package]
name = "qp-dev-cli"
edition = "2021"
publish = false

[[bin]]
name = "qp-dev-cli"
path = "src/main.rs"

[dependencies]
hive-router-query-planner = { path = "../../lib/query-planner" }
hive-router-plan-executor = { path = "../../lib/executor" }
graphql-tools =  { path = "../../lib/graphql-tools" }

tracing-subscriber = { workspace = true }
tracing-tree = { workspace = true }
serde_json = { workspace = true }
