# yaml-language-server: $schema=router-config.schema.json
supergraph:
  source: file
  path: ./bench/supergraph.graphql
log:
  service:
    exporters:
      - kind: stdout
        level: debug
        format: json
