# yaml-language-server: $schema=router-config.schema.json
supergraph:
  source: file
  path: ./bench/supergraph.graphql
log:
  service:
    level: debug
    format: json
    log_fields:
      http:
        request:
          method: true
          path: true
        response:
          status_code: true
          duration_ms: true
