[workspace]
allow_dirty = true
changelog_update = true
git_release_enable = true
git_tag_enable = true

[[package]]
name = "qp-dev-cli"
release = false
publish = false

[[package]]
name = "subgraphs"
release = false
publish = false

[[package]]
name = "hive-router"
changelog_include = [
  "hive-router-plan-executor",
  "hive-router-config",
  "hive-router-query-planner",
]

[changelog]
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->New Features" },
    { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
    { message = "^docs", group = "<!-- 4 -->Documentation" },
    { message = "^refactor", group = "<!-- 2 -->Refactoring" },
    { message = "^perf", group = "<!-- 3 -->Performance" },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
    { message = "^.*", group = "<!-- 5 -->Other" },
]
