[package]
name = "hive-router"
version = "0.0.39"
edition = "2021"
description = "GraphQL router/gateway for Federation"
license = "MIT"
publish = true
authors = ["The Guild"]
repository = "https://github.com/graphql-hive/router"
homepage = "https://github.com/graphql-hive/router"
readme = "README.crate.md"

[lib]

[[bin]]
name = "hive_router"
path = "src/main.rs"

[features]
noop_otlp_exporter = ["hive-router-internal/noop_otlp_exporter"]
testing = []

[dependencies]
hive-router-query-planner = { path = "../../lib/query-planner", version = "2.2.1" }
hive-router-plan-executor = { path = "../../lib/executor", version = "6.5.1" }
hive-router-config = { path = "../../lib/router-config", version = "0.0.23" }
hive-router-internal = { path = "../../lib/internal", version = "0.0.12" }
hive-console-sdk = { path = "../../lib/hive-console-sdk", version = "0.3.6" }
graphql-tools =  { path = "../../lib/graphql-tools", version = "0.5.1" }

tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }
sonic-rs = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-tree = { workspace = true }
hyper = { workspace = true, features = ["server", "http1"] }
http = { workspace = true }
http-body-util = { workspace = true }
thiserror = { workspace = true }
lazy_static = { workspace = true }
async-trait = { workspace = true }
xxhash-rust = { workspace = true }
rand = { workspace = true }
ntex = { workspace = true }
jsonwebtoken = { workspace = true }
retry-policies = { workspace = true}
reqwest-retry = { workspace = true }
reqwest-middleware = { workspace = true }
vrl = { workspace = true }
serde_json = { workspace = true }
regex-automata = { workspace = true }
ahash = { workspace = true }
rustls = { workspace = true, features = ["aws-lc-rs"] }
hyper-rustls = { workspace = true, features = ["aws-lc-rs"]}
dashmap = { workspace = true }

moka = { workspace = true }
ulid = "1.2.1"
tokio-util = { workspace = true }
cookie = "0.18.1"
arc-swap = { workspace = true }
lasso2 = "0.8.2"
anyhow = { workspace = true }
combine = { workspace = true }
strum = { workspace = true }
insta = { workspace = true }

mimalloc = { version = "0.1.48", features = ["v3"] }
mediatype = "0.21.0"
headers-accept = "0.3.0"
md5 = "0.8.0"

[dev-dependencies]
criterion = { workspace = true }
insta = { workspace = true }

[[bench]]
name = "router_benches"
harness = false
