# yaml-language-server: $schema=../../router-config.schema.json
supergraph:
  source: file
  path: ../../e2e/supergraph.graphql
plugins:
  jwt_cookie:
    enabled: true
    config:
      refresh_endpoint: http://0.0.0.0:9876
