[package]
name = "e2e"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
ntex = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
sonic-rs = { workspace = true }
lazy_static = { workspace = true }
jsonwebtoken = { workspace = true }
insta = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
dashmap = { workspace = true }
async-trait = { workspace = true }
http = { workspace = true }
bytes = { workspace = true }
graphql-tools = { workspace = true }
graphql-parser = { workspace = true }

hive-router = { path = "../bin/router" }
hive-router-config = { path = "../lib/router-config" }
hive-router-plan-executor = { path = "../lib/executor" }
hive-router-query-planner = { path = "../lib/query-planner" }
subgraphs = { path = "../bench/subgraphs" }

mockito = "1.7.0"
tempfile = "3.23.0"
redis = "0.32.7"
multer = "3.1.0"
futures-util = "0.3.31"

