# The following are aliases you can use with "cargo command_name"
[alias]
router = "run --package hive-router"
dev = "run --package qp-dev-cli"
subgraphs = "run --package subgraphs"
test_qp = "test --package hive-router-query-planner -- --nocapture"
test_all = "test --workspace --exclude e2e --exclude *-plugin-example"
test_e2e = "test --package e2e -- --test-threads=5"
test_qpe = "test --package hive-router-plan-executor -- --nocapture"
test_plugin_examples = "test --package *-plugin-example --jobs 1 -- --nocapture --test-threads=1"
"clippy:fix" = "clippy --all --fix --allow-dirty --allow-staged"
"router-config" = "run --release -p hive-router-config router-config.schema.json"
