# The following are aliases you can use with "cargo command_name"
[alias]
router = "run --package hive-router"
dev = "run --package qp-dev-cli"
subgraphs = "run --package subgraphs"
test_qp = "test --package hive-router-query-planner -- --nocapture"
test_all = "test --workspace --exclude e2e"
test_e2e = "test --package e2e --jobs 1 -- --nocapture --test-threads=1"
test_qpe = "test --package hive-router-plan-executor -- --nocapture"
"clippy:fix" = "clippy --all --fix --allow-dirty --allow-staged"
"router-config" = "run --release -p hive-router-config router-config.schema.json"

[build]
rustflags = ["--cfg", "tracing_unstable"]
